# Generated by Django 5.0.7 on 2024-09-22 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npkreadings', '0001_initial'),
       
    ]

    operations = [
        migrations.AlterField(
            model_name='npkreading',
            name='recommendation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NpkReading', to='recommendation.recommendation'),
        ),
    ]
