# Generated by Django 5.0.7 on 2024-09-22 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npkreadings', '0002_alter_npkreading_recommendation_id'),
        ('recommendation', '0002_rename_recommendations_content_recommendation_recommendation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npkreading',
            name='recommendation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NpkReading', to='recommendation.recommendation'),
        ),
    ]
