# Generated by Django 5.1.1 on 2024-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_value', models.CharField(choices=[('acidic', 'Acidic'), ('neutral', 'Neutral'), ('alkaline', 'Alkaline')], max_length=10)),
                ('farmer_id', models.IntegerField()),
                ('ph_id', models.IntegerField()),
            ],
        ),
    ]
