# Generated by Django 5.1.1 on 2024-09-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npkreading', '0001_initial'),
        ('recommendations', '0002_remove_recommendations_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npkreadings',
            name='npk_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='npkreadings',
            name='recommendation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_content', to='recommendations.recommendations'),
        ),
    ]
