# Generated by Django 5.1.1 on 2024-09-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npkreading', '0002_alter_npkreadings_npk_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npkreadings',
            old_name='npk_id',
            new_name='id',
        ),
    ]
