# Generated by Django 5.1.1 on 2024-09-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npkreading', '0003_rename_npk_id_npkreadings_id'),
        ('recommendations', '0003_rename_recommendations_id_recommendations_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpkReading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_id', models.IntegerField()),
                ('sensor_id', models.IntegerField()),
                ('npk_reading', models.IntegerField()),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NpkReading', to='recommendations.recommendations')),
            ],
        ),
        migrations.DeleteModel(
            name='Npkreadings',
        ),
    ]
