# Generated by Django 5.1.1 on 2024-09-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npkreading', '0004_npkreading_delete_npkreadings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npkreading',
            old_name='recommendation',
            new_name='recommendation_id',
        ),
    ]
