# Generated by Django 5.0 on 2024-09-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph_reading", models.FloatField()),
                ("moisture_reading", models.FloatField()),
                ("nutrients", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.farmer"
                    ),
                ),
            ],
        ),
    ]
