# Generated by Django 5.1.1 on 2024-09-20 09:12

import django.db.models.deletion
import sendsms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0002_sensordata_delete_cronjoblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='farm',
            field=models.ForeignKey(to='Farm',on_delete=models.CASCADE, related_name='sensor_data'),  ),
    ]
