# Generated by Django 5.1.1 on 2024-09-20 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0005_remove_sensordata_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='sendsms.farm'),
        ),
    ]
