# Generated by Django 5.1.1 on 2024-09-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0008_alter_sensordata_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sendsms.farm'),
        ),
    ]
