# Generated by Django 5.1.1 on 2024-09-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0014_remove_sensordata_farm_delete_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
