# Generated by Django 5.1.1 on 2024-09-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        ('sendsms', '0015_sensordata_phone_number'),
        ('sensorreadings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='farmer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensorreadings.sensorreadings'),
            preserve_default=False,
        ),
    ]
