# Generated by Django 5.1.1 on 2024-09-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensorreadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('moisture_readings', models.IntegerField()),
                ('npk_readings', models.IntegerField()),
                ('ph_reading', models.IntegerField()),
                ('farmer_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
