# Generated by Django 5.1.1 on 2024-09-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorreadings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensorreadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('moisture_readings', models.IntegerField()),
                ('npk_readings', models.IntegerField()),
                ('ph_reading', models.IntegerField()),
                ('farmer_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Phreadings',
        ),
    ]
