# Generated by Django 5.1.1 on 2024-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorreadings', '0002_sensorreadings_delete_phreadings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreadings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
