# Generated by Django 5.1.1 on 2024-09-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorreadings', '0003_sensorreadings_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreadings',
            name='is_active',
        ),
    ]
