# Generated by Django 5.1.1 on 2024-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('farmer_id', models.IntegerField()),
                ('sensor_id', models.IntegerField()),
                ('recommendation_inactive', models.BooleanField(default=False)),
            ],
        ),
    ]
