# Generated by Django 5.1.1 on 2024-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='id',
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommendations_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
