# Generated by Django 5.1.1 on 2024-09-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_recommendations_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendations',
            old_name='recommendations_id',
            new_name='id',
        ),
    ]
