# Generated by Django 5.1.1 on 2024-09-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npkreadings', '0002_alter_npkreading_recommendation_id'),
        ('recommendations', '0002_recommendations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
