# Generated by Django 5.1.1 on 2024-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_rename_recommendations_id_recommendations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
