# Generated by Django 5.1.1 on 2024-09-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='inactive',
            new_name='recommendation_inactive',
        ),
    ]
