# Generated by Django 5.0.7 on 2024-09-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommendations_content',
            new_name='recommendation_content',
        ),
    ]
