# Generated by Django 5.1.1 on 2024-09-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_farmer_phone_number'),
        ('recommendation', '0002_remove_recommendation_recommendations_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='farmer',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='farmer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_text',
            field=models.TextField(default='No recommendations for this value'),
        ),
    ]
