# Generated by Django 5.1.1 on 2024-09-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moisturereadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('farmer_id', models.IntegerField()),
                ('moisture_readings', models.IntegerField()),
                ('moisture_id', models.IntegerField()),
                ('recommendation_id', models.IntegerField()),
            ],
        ),
    ]
