# Generated by Django 5.1.1 on 2024-09-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inactivestatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
    ]
