# Generated by Django 5.1.1 on 2024-09-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_farmer_phone_number'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommendations_content',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
           model_name='recommendation',
           name='farmer_id',
          field=models.ForeignKey(to='farmer.Farmer', on_delete=models.CASCADE),
)

    ]
