# Generated by Django 5.0 on 2024-09-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendation",
            old_name="recommendation_text",
            new_name="recommendation_content",
        ),
    ]
