# Generated by Django 5.1.1 on 2024-09-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npkreadings', '0001_initial'),
        ('recommendations', '0002_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npkreading',
            name='recommendation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NpkReading', to='recommendations.recommendations'),
        ),
    ]
