# Generated by Django 5.1.1 on 2024-09-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('output', models.TextField()),
                ('locked_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sendsms',
            fields=[
                ('sender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=20)),
                ('farmer_id', models.IntegerField()),
                ('sensor_id', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
