# Generated by Django 5.1.1 on 2024-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sendsms',
            fields=[
                ('sender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=20)),
                ('farmer_id', models.IntegerField()),
                ('sensor_id', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
