# Generated by Django 5.1.1 on 2024-09-12 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsms',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sendsms',
            name='send_sms_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
