# Generated by Django 5.1.1 on 2024-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0002_remove_sendsms_sensor_id_sendsms_send_sms_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsms',
            name='send_sms_id',
        ),
        migrations.AddField(
            model_name='sendsms',
            name='sensor_id',
            field=models.IntegerField(default=0),
        ),
    ]
