# Generated by Django 5.1.1 on 2024-09-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0004_sensordata_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='phone_number',
        ),
    ]
