# Generated by Django 5.1.1 on 2024-09-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        ('sendsms', '0011_alter_sensordata_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendsms',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='sendsms',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sendsms',
            name='farmer_id_sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_id_sms', to='farmer.farmer'),
        ),
        migrations.AddField(
            model_name='sendsms',
            name='sensor_id_sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_id_sms', to='farmer.farmer'),
        ),
    ]
