# Generated by Django 5.1.1 on 2024-09-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0012_remove_sendsms_farmer_id_remove_sendsms_sensor_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sendsms',
        ),
    ]
