# Generated by Django 5.1.1 on 2024-09-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0013_delete_sendsms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='farm',
        ),
        migrations.DeleteModel(
            name='Farm',
        ),
    ]
