# Generated by Django 5.1.1 on 2024-09-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        ('sendsms', '0016_remove_sensordata_phone_number_sensordata_farmer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='farmer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
    ]
