# Generated by Django 5.1.1 on 2024-09-22 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_farmer_phone_number'),
        ('sendsms', '0017_alter_sensordata_farmer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
    ]
