# Generated by Django 5.1.1 on 2024-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0018_remove_sensordata_sensor_id_sensordata_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='nutrients',
            field=models.IntegerField(),
        ),
    ]
